// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkspaceDirectory(arg1:string):Promise<void>;

export function AskProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AskScoped(arg1:string,arg2:string):Promise<void>;

export function CreateWorkspace(arg1:string):Promise<string>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function Doctor():Promise<void>;

export function ListAgents(arg1:string):Promise<string>;

export function ListPipelines(arg1:string):Promise<string>;

export function ListProviders():Promise<string>;

export function ListWorkspaces():Promise<string>;

export function LoadMessages(arg1:string):Promise<string>;

export function Ready():Promise<void>;

export function RemoveWorkspaceDirectory(arg1:string,arg2:string):Promise<void>;

export function RunPipeline(arg1:string,arg2:string):Promise<void>;

export function SaveMessage(arg1:string,arg2:string):Promise<void>;

export function SavePipeline(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateWorkspaceTitle(arg1:string,arg2:string):Promise<void>;
