// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkspaceDirectory(arg1:string):Promise<void>;

export function AnswerClarification(arg1:string,arg2:string):Promise<void>;

export function AskProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AskScoped(arg1:string,arg2:string):Promise<void>;

export function CreatePrompt(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateWorkspace(arg1:string):Promise<string>;

export function DeleteChatWorkflow(arg1:number):Promise<void>;

export function DeletePrompt(arg1:number):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function Doctor():Promise<void>;

export function GetWorkflowFileDetails(arg1:string):Promise<string>;

export function ListAgents(arg1:string):Promise<string>;

export function ListChatWorkflows(arg1:string):Promise<string>;

export function ListPrompts():Promise<string>;

export function ListProviders():Promise<string>;

export function ListWorkflows(arg1:string):Promise<string>;

export function ListWorkspaces():Promise<string>;

export function LoadMessages(arg1:string):Promise<string>;

export function Ready():Promise<void>;

export function RemoveWorkspaceDirectory(arg1:string,arg2:string):Promise<void>;

export function RunChain(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RunWorkflow(arg1:string,arg2:string):Promise<void>;

export function SaveChatWorkflow(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveMessage(arg1:string,arg2:string):Promise<void>;

export function SaveWorkflow(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateChatWorkflow(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateWorkspaceTitle(arg1:string,arg2:string):Promise<void>;
