// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkspaceDirectory(arg1) {
  return window['go']['main']['App']['AddWorkspaceDirectory'](arg1);
}

export function AgentPathForName(arg1, arg2) {
  return window['go']['main']['App']['AgentPathForName'](arg1, arg2);
}

export function AnswerClarification(arg1, arg2) {
  return window['go']['main']['App']['AnswerClarification'](arg1, arg2);
}

export function AskProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AskProvider'](arg1, arg2, arg3, arg4, arg5);
}

export function AskScoped(arg1, arg2) {
  return window['go']['main']['App']['AskScoped'](arg1, arg2);
}

export function BrainDecisions(arg1) {
  return window['go']['main']['App']['BrainDecisions'](arg1);
}

export function CollectorsConfigPath(arg1) {
  return window['go']['main']['App']['CollectorsConfigPath'](arg1);
}

export function CreateDraft(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateDraft'](arg1, arg2, arg3, arg4);
}

export function CreateDraftFromTarget(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateDraftFromTarget'](arg1, arg2, arg3, arg4);
}

export function CreatePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteDraft(arg1) {
  return window['go']['main']['App']['DeleteDraft'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteWorkflowFile(arg1) {
  return window['go']['main']['App']['DeleteWorkflowFile'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function Doctor(arg1) {
  return window['go']['main']['App']['Doctor'](arg1);
}

export function GetCollectorsConfigJSON(arg1) {
  return window['go']['main']['App']['GetCollectorsConfigJSON'](arg1);
}

export function GetDraft(arg1) {
  return window['go']['main']['App']['GetDraft'](arg1);
}

export function GetWorkflowFileDetails(arg1) {
  return window['go']['main']['App']['GetWorkflowFileDetails'](arg1);
}

export function ListAgents(arg1) {
  return window['go']['main']['App']['ListAgents'](arg1);
}

export function ListCollectors(arg1) {
  return window['go']['main']['App']['ListCollectors'](arg1);
}

export function ListDrafts(arg1, arg2) {
  return window['go']['main']['App']['ListDrafts'](arg1, arg2);
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListWorkflows(arg1) {
  return window['go']['main']['App']['ListWorkflows'](arg1);
}

export function ListWorkspaceDirectoriesDetailed(arg1) {
  return window['go']['main']['App']['ListWorkspaceDirectoriesDetailed'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LoadMessages(arg1) {
  return window['go']['main']['App']['LoadMessages'](arg1);
}

export function PromoteDraft(arg1, arg2) {
  return window['go']['main']['App']['PromoteDraft'](arg1, arg2);
}

export function PromoteDraftAs(arg1, arg2) {
  return window['go']['main']['App']['PromoteDraftAs'](arg1, arg2);
}

export function ReadCollectorsConfig(arg1) {
  return window['go']['main']['App']['ReadCollectorsConfig'](arg1);
}

export function ReadSkillOrAgentFile(arg1) {
  return window['go']['main']['App']['ReadSkillOrAgentFile'](arg1);
}

export function ReadWorkflowFile(arg1) {
  return window['go']['main']['App']['ReadWorkflowFile'](arg1);
}

export function Ready() {
  return window['go']['main']['App']['Ready']();
}

export function RecentCollectorLogs(arg1) {
  return window['go']['main']['App']['RecentCollectorLogs'](arg1);
}

export function RefineDraft(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RefineDraft'](arg1, arg2, arg3, arg4);
}

export function RemoveWorkspaceDirectory(arg1, arg2) {
  return window['go']['main']['App']['RemoveWorkspaceDirectory'](arg1, arg2);
}

export function RunChain(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunChain'](arg1, arg2, arg3, arg4, arg5);
}

export function RunWorkflow(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunWorkflow'](arg1, arg2, arg3);
}

export function SaveChatWorkflow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveChatWorkflow'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveMessage(arg1, arg2) {
  return window['go']['main']['App']['SaveMessage'](arg1, arg2);
}

export function SaveWorkflow(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWorkflow'](arg1, arg2, arg3);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['main']['App']['SetActiveWorkspace'](arg1);
}

export function SetWorkspaceDirectoryEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWorkspaceDirectoryEnabled'](arg1, arg2, arg3);
}

export function SkillPathForName(arg1, arg2) {
  return window['go']['main']['App']['SkillPathForName'](arg1, arg2);
}

export function StepThroughAbort(arg1) {
  return window['go']['main']['App']['StepThroughAbort'](arg1);
}

export function StepThroughAccept(arg1) {
  return window['go']['main']['App']['StepThroughAccept'](arg1);
}

export function StepThroughEditOutput(arg1, arg2) {
  return window['go']['main']['App']['StepThroughEditOutput'](arg1, arg2);
}

export function StepThroughSave(arg1, arg2) {
  return window['go']['main']['App']['StepThroughSave'](arg1, arg2);
}

export function StepThroughSnapshot(arg1) {
  return window['go']['main']['App']['StepThroughSnapshot'](arg1);
}

export function StepThroughStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['StepThroughStart'](arg1, arg2, arg3);
}

export function StepThroughStartFromChain(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StepThroughStartFromChain'](arg1, arg2, arg3, arg4, arg5);
}

export function StopDraftRefine(arg1) {
  return window['go']['main']['App']['StopDraftRefine'](arg1);
}

export function StopRun(arg1) {
  return window['go']['main']['App']['StopRun'](arg1);
}

export function UpdateDraftBody(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateDraftBody'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateWorkspaceTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkspaceTitle'](arg1, arg2);
}

export function WorkflowPathForName(arg1, arg2) {
  return window['go']['main']['App']['WorkflowPathForName'](arg1, arg2);
}

export function WriteCollectorsConfig(arg1, arg2) {
  return window['go']['main']['App']['WriteCollectorsConfig'](arg1, arg2);
}

export function WriteCollectorsConfigJSON(arg1, arg2) {
  return window['go']['main']['App']['WriteCollectorsConfigJSON'](arg1, arg2);
}

export function WriteWorkflowFile(arg1, arg2) {
  return window['go']['main']['App']['WriteWorkflowFile'](arg1, arg2);
}
