// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkspaceDirectory(arg1) {
  return window['go']['main']['App']['AddWorkspaceDirectory'](arg1);
}

export function AskProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AskProvider'](arg1, arg2, arg3, arg4, arg5);
}

export function AskScoped(arg1, arg2) {
  return window['go']['main']['App']['AskScoped'](arg1, arg2);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function Doctor() {
  return window['go']['main']['App']['Doctor']();
}

export function ListAgents(arg1) {
  return window['go']['main']['App']['ListAgents'](arg1);
}

export function ListPipelines(arg1) {
  return window['go']['main']['App']['ListPipelines'](arg1);
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LoadMessages(arg1) {
  return window['go']['main']['App']['LoadMessages'](arg1);
}

export function Ready() {
  return window['go']['main']['App']['Ready']();
}

export function RemoveWorkspaceDirectory(arg1, arg2) {
  return window['go']['main']['App']['RemoveWorkspaceDirectory'](arg1, arg2);
}

export function RunPipeline(arg1, arg2) {
  return window['go']['main']['App']['RunPipeline'](arg1, arg2);
}

export function SaveMessage(arg1, arg2) {
  return window['go']['main']['App']['SaveMessage'](arg1, arg2);
}

export function SavePipeline(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePipeline'](arg1, arg2, arg3);
}

export function UpdateWorkspaceTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkspaceTitle'](arg1, arg2);
}
