package chatui

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"sync"
	"time"
)

// threads.go is the data model for the chat-threads openspec change. It
// introduces two new exported types — `ChatMessage` and `Thread` — alongside
// an in-memory `ThreadStore` that the desktop UI and the test suite share.
//
// Three rules from the openspec proposal drive this file:
//
//   - "A thread cannot spawn a sub-thread in v1 — the parent-child
//     relationship is flat." Spawn rejects parents whose own ParentMessageID
//     is non-empty.
//
//   - "Closing a thread emits a thread_closed event, optionally captures a
//     one-line summary on the parent message, and freezes further input."
//     Close stamps the summary on the Thread, transitions State, and
//     records the timestamp; subsequent Append calls return ErrThreadClosed.
//
//   - "Reloading a session re-creates the thread tree." The store is built
//     so a future persistence layer can serialise it as `messages.json` +
//     `threads.json` and reload by walking messages, grouping by ParentID,
//     and re-attaching the Thread records. The current in-memory store is
//     a placeholder for that wiring; tests construct it directly.
//
// The legacy `message` type in messages.go stays put: existing chat code
// paths in glitch-desktop still use it. ChatMessage is the new richer
// message that carries Type + Payload, and the two coexist while the
// frontend migration lands.

// MessageType discriminates the structured payloads a chat message can
// carry. The values are chosen to round-trip cleanly through JSON without
// requiring a custom marshaller — they are plain strings the renderer
// switches on.
type MessageType string

const (
	// MessageTypeText is the default markdown-only message — what the
	// existing chat already produces. Payload is a TextPayload.
	MessageTypeText MessageType = "text"
	// MessageTypeWidgetCard is a structured card the assistant emits in
	// response to a slash command (e.g. /status, /brain config).
	// Payload is a WidgetCardPayload.
	MessageTypeWidgetCard MessageType = "widget_card"
	// MessageTypeActionChips is a row of clickable chips a card or
	// previous assistant message can attach as follow-up actions.
	// Payload is an ActionChipsPayload.
	MessageTypeActionChips MessageType = "action_chips"
	// MessageTypeEvidenceBundle renders a research-loop EvidenceBundle
	// inline so the user can see what the loop gathered without leaving
	// chat. Payload is an EvidenceBundlePayload.
	MessageTypeEvidenceBundle MessageType = "evidence_bundle"
	// MessageTypeScoreCard renders a metric (composite confidence,
	// signal counts) so the user can see how the loop scored a draft.
	// Payload is a ScoreCardPayload.
	MessageTypeScoreCard MessageType = "score_card"
	// MessageTypeAttentionFeed renders the activity feed as the idle
	// default content of a chat panel. Payload is an
	// AttentionFeedPayload.
	MessageTypeAttentionFeed MessageType = "attention_feed"
)

// Role is the speaker of a chat message. The legacy `role int` type stays
// in messages.go; this is the exported string version the new threads UI
// uses so JSON output is human-readable.
type Role string

const (
	RoleUser      Role = "user"
	RoleAssistant Role = "assistant"
	RoleSystem    Role = "system"
)

// ChatMessage is the richer message type the threaded UI consumes. It
// carries a Type + Payload pair so a single message can render as text,
// a widget card, an evidence bundle, etc. without forcing the renderer to
// inspect markdown for cues.
type ChatMessage struct {
	ID              string      `json:"id"`
	ParentMessageID string      `json:"parent_message_id,omitempty"`
	ThreadID        string      `json:"thread_id,omitempty"`
	Role            Role        `json:"role"`
	Type            MessageType `json:"type"`
	Payload         any         `json:"payload"`
	CreatedAt       time.Time   `json:"created_at"`
	// SyntheticOrigin records the source widget message ID when this
	// message was generated by a chip click rather than typed by the
	// user. The brain audit consumes it (chat-first-ui task 7.3); the
	// renderer ignores it.
	SyntheticOrigin string `json:"synthetic_origin,omitempty"`
}

// TextPayload is the payload for MessageTypeText.
type TextPayload struct {
	Body string `json:"body"`
}

// WidgetCardPayload is the payload for MessageTypeWidgetCard.
type WidgetCardPayload struct {
	Title    string         `json:"title"`
	Subtitle string         `json:"subtitle,omitempty"`
	Rows     []WidgetRow    `json:"rows,omitempty"`
	Actions  []ActionChip   `json:"actions,omitempty"`
}

// WidgetRow is one key/value row inside a widget card.
type WidgetRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// ActionChip is one clickable chip on a widget card or in an action_chips
// message. Clicks construct a synthetic chat input message containing the
// Command field and route it back through the dispatcher — see chat-first-
// ui task 7.2.
type ActionChip struct {
	Label   string `json:"label"`
	Command string `json:"command"`
	// Disabled marks a chip as inert. Used when re-rendering chips
	// loaded from history (the click would have no effect because the
	// session has moved on) so the user knows visually it is read-only.
	Disabled bool `json:"disabled,omitempty"`
}

// ActionChipsPayload is the payload for MessageTypeActionChips.
type ActionChipsPayload struct {
	Chips []ActionChip `json:"chips"`
}

// EvidenceBundlePayload mirrors a research.EvidenceBundle but is defined
// here so internal/chatui does not depend on internal/research. The
// adapter that converts a research.Result into a chat message lives in
// glitch-desktop (or whatever caller is bridging the two), keeping the
// chatui package self-contained.
type EvidenceBundlePayload struct {
	Items     []EvidenceBundleItem `json:"items"`
	Composite float64              `json:"composite,omitempty"`
}

// EvidenceBundleItem is one row in an evidence bundle widget.
type EvidenceBundleItem struct {
	Source string   `json:"source"`
	Title  string   `json:"title"`
	Body   string   `json:"body"`
	Refs   []string `json:"refs,omitempty"`
}

// ScoreCardPayload is the payload for MessageTypeScoreCard.
type ScoreCardPayload struct {
	Metric string  `json:"metric"`
	Value  float64 `json:"value"`
	// Sparkline is a series of recent values for the same metric so
	// the renderer can draw a tiny trend line. May be empty.
	Sparkline []float64 `json:"sparkline,omitempty"`
}

// AttentionFeedPayload is the payload for MessageTypeAttentionFeed.
type AttentionFeedPayload struct {
	Items []AttentionItem `json:"items"`
}

// AttentionItem is one row of the attention feed.
type AttentionItem struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Snippet   string    `json:"snippet,omitempty"`
	Severity  string    `json:"severity,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	// Action is the slash command a click on this item should run.
	// Empty when the item is purely informational.
	Action string `json:"action,omitempty"`
}

// ThreadState is the lifecycle state of a thread.
type ThreadState string

const (
	// ThreadOpen accepts new messages.
	ThreadOpen ThreadState = "open"
	// ThreadClosed is read-only. Re-opening transitions back to open.
	ThreadClosed ThreadState = "closed"
)

// ExpandPref is the user's preferred render mode for one thread. Persisted
// per thread so re-opening a session uses the same mode the user last
// chose.
type ExpandPref string

const (
	// ExpandInline renders the thread inline below its parent message.
	ExpandInline ExpandPref = "inline"
	// ExpandSidePane renders the thread in the right-hand pane.
	ExpandSidePane ExpandPref = "side-pane"
	// ExpandCollapsed shows only the parent message and a reply count.
	ExpandCollapsed ExpandPref = "collapsed"
)

// Thread is one sub-conversation hanging off a parent message.
type Thread struct {
	ID              string      `json:"id"`
	ParentMessageID string      `json:"parent_message_id"`
	State           ThreadState `json:"state"`
	Summary         string      `json:"summary,omitempty"`
	LastActivityAt  time.Time   `json:"last_activity_at"`
	ExpandPref      ExpandPref  `json:"expand_pref,omitempty"`
	// CreatedAt is the wall-clock time the thread was spawned, used to
	// order threads when listing them under a parent.
	CreatedAt time.Time `json:"created_at"`
}

// Errors returned by ThreadStore methods.
var (
	ErrParentNotFound = errors.New("chatui: parent message not found")
	ErrNestingForbidden = errors.New("chatui: cannot spawn a thread under a message that is itself in a thread")
	ErrThreadNotFound = errors.New("chatui: thread not found")
	ErrThreadClosed   = errors.New("chatui: thread is closed")
)

// ThreadStore is the in-memory data plane for the threaded chat. It owns
// both the message log and the thread tree, so a single Spawn / Append /
// Close call updates both consistently. The store is safe for concurrent
// reads and writes — all access goes through the embedded mutex.
//
// The store is intentionally agnostic about persistence: a future on-disk
// layer can wrap it (Append → write JSONL line, reload → replay) without
// changing any caller. The desktop app uses one store per session.
type ThreadStore struct {
	mu       sync.RWMutex
	messages map[string]*ChatMessage
	order    []string // message IDs in append order; the main-chat scrollback
	threads  map[string]*Thread
	// byParent indexes threads by their parent message ID so the
	// renderer can ask "is there a thread under message X?" in O(1).
	byParent map[string]string
}

// NewThreadStore constructs an empty ThreadStore.
func NewThreadStore() *ThreadStore {
	return &ThreadStore{
		messages: make(map[string]*ChatMessage),
		threads:  make(map[string]*Thread),
		byParent: make(map[string]string),
	}
}

// Append adds a message to the store and returns it (with ID populated).
// If ThreadID is set, the message is appended to that thread; otherwise
// it appends to the main chat scrollback.
//
// Append rejects messages whose ThreadID points at a closed thread —
// closed threads are read-only by spec. Reopening must happen first.
func (s *ThreadStore) Append(msg ChatMessage) (ChatMessage, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if msg.ID == "" {
		msg.ID = newID("m")
	}
	if msg.CreatedAt.IsZero() {
		msg.CreatedAt = time.Now()
	}
	if msg.Type == "" {
		msg.Type = MessageTypeText
	}

	if msg.ThreadID != "" {
		t, ok := s.threads[msg.ThreadID]
		if !ok {
			return ChatMessage{}, fmt.Errorf("%w: %s", ErrThreadNotFound, msg.ThreadID)
		}
		if t.State == ThreadClosed {
			return ChatMessage{}, fmt.Errorf("%w: %s", ErrThreadClosed, msg.ThreadID)
		}
		t.LastActivityAt = msg.CreatedAt
	}

	stored := msg
	s.messages[stored.ID] = &stored
	s.order = append(s.order, stored.ID)
	return stored, nil
}

// Spawn creates a new thread under the given parent message. Returns the
// new Thread (with ID populated). Spawn rejects parents that are
// themselves inside a thread — the spec forbids nesting in v1.
//
// Parent IDs do NOT have to exist in this store. The desktop's main chat
// has its own message persistence (glitchd.SaveMessage), and we want
// every legacy message to be threadable without first re-importing it
// into the chatui store. The contract is: parentMessageID is an opaque
// stable identifier; the caller is responsible for choosing one that
// makes sense to their renderer.
func (s *ThreadStore) Spawn(parentMessageID string, expand ExpandPref) (Thread, error) {
	if parentMessageID == "" {
		return Thread{}, fmt.Errorf("%w: empty id", ErrParentNotFound)
	}
	s.mu.Lock()
	defer s.mu.Unlock()

	// If we happen to have the parent in our own store, enforce the
	// no-nesting rule. Otherwise treat the parent as opaque.
	if parent, ok := s.messages[parentMessageID]; ok {
		if parent.ThreadID != "" {
			return Thread{}, ErrNestingForbidden
		}
	}
	if existing, ok := s.byParent[parentMessageID]; ok {
		// One thread per parent message — calling Spawn twice on the
		// same parent returns the existing thread, so callers can be
		// idempotent without checking first.
		return *s.threads[existing], nil
	}

	if expand == "" {
		expand = ExpandInline
	}
	now := time.Now()
	t := Thread{
		ID:              newID("t"),
		ParentMessageID: parentMessageID,
		State:           ThreadOpen,
		ExpandPref:      expand,
		LastActivityAt:  now,
		CreatedAt:       now,
	}
	s.threads[t.ID] = &t
	s.byParent[parentMessageID] = t.ID
	return t, nil
}

// LookupByParent returns the thread hanging off the given parent message,
// if one exists.
func (s *ThreadStore) LookupByParent(parentMessageID string) (Thread, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	id, ok := s.byParent[parentMessageID]
	if !ok {
		return Thread{}, false
	}
	return *s.threads[id], true
}

// LookupByID returns the thread with the given ID, if it exists.
func (s *ThreadStore) LookupByID(id string) (Thread, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	t, ok := s.threads[id]
	if !ok {
		return Thread{}, false
	}
	return *t, true
}

// Close transitions a thread to ThreadClosed and stamps the supplied
// summary on it. Returns ErrThreadNotFound when the ID is unknown. Closing
// a thread that is already closed is a no-op (the existing summary is
// preserved unless a non-empty new summary is supplied).
func (s *ThreadStore) Close(threadID, summary string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	t, ok := s.threads[threadID]
	if !ok {
		return fmt.Errorf("%w: %s", ErrThreadNotFound, threadID)
	}
	t.State = ThreadClosed
	if summary != "" {
		t.Summary = summary
	}
	t.LastActivityAt = time.Now()
	return nil
}

// Reopen transitions a closed thread back to ThreadOpen.
func (s *ThreadStore) Reopen(threadID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	t, ok := s.threads[threadID]
	if !ok {
		return fmt.Errorf("%w: %s", ErrThreadNotFound, threadID)
	}
	t.State = ThreadOpen
	t.LastActivityAt = time.Now()
	return nil
}

// MainScrollback returns the messages that live in the root context
// (ThreadID == "") in append order. The renderer uses this for the main
// chat panel.
func (s *ThreadStore) MainScrollback() []ChatMessage {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]ChatMessage, 0, len(s.order))
	for _, id := range s.order {
		m := s.messages[id]
		if m == nil || m.ThreadID != "" {
			continue
		}
		out = append(out, *m)
	}
	return out
}

// ThreadMessages returns the messages inside the given thread, in append
// order. Returns an empty slice (not an error) when the thread has no
// messages yet, so renderers can call this immediately after Spawn.
func (s *ThreadStore) ThreadMessages(threadID string) []ChatMessage {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]ChatMessage, 0)
	for _, id := range s.order {
		m := s.messages[id]
		if m == nil || m.ThreadID != threadID {
			continue
		}
		out = append(out, *m)
	}
	return out
}

// RemoveLastMain removes the most recently appended main-chat message
// (a message with no ThreadID). It is the small surgical helper the
// desktop's "freeform → research thread" routing uses to undo the
// echoed user line before swapping in a richer parent card.
//
// No-op when the most recent message is in a thread or when the store
// is empty. Thread membership is checked from the tail of the order
// slice — only main-chat messages are eligible for removal.
func (s *ThreadStore) RemoveLastMain() {
	s.mu.Lock()
	defer s.mu.Unlock()
	for i := len(s.order) - 1; i >= 0; i-- {
		id := s.order[i]
		m, ok := s.messages[id]
		if !ok {
			continue
		}
		if m.ThreadID != "" {
			// We only remove from the tail; if the tail is in a
			// thread, there is no main-chat message to remove.
			return
		}
		s.order = append(s.order[:i], s.order[i+1:]...)
		delete(s.messages, id)
		return
	}
}

// AllThreads returns every thread in the store, ordered by CreatedAt.
// Useful for the persistence layer (serialise on shutdown) and for the
// /threads slash command.
func (s *ThreadStore) AllThreads() []Thread {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]Thread, 0, len(s.threads))
	for _, t := range s.threads {
		out = append(out, *t)
	}
	return out
}

// newID returns a 16-hex-char identifier with a one-letter prefix. Stable
// enough for in-process use; the persistence layer can rewrite IDs to its
// own scheme on serialise/deserialise without breaking anything.
func newID(prefix string) string {
	var buf [8]byte
	if _, err := rand.Read(buf[:]); err != nil {
		// crypto/rand failures are absurdly rare; fall back to a
		// timestamp so the call site never panics on ID generation.
		return prefix + "-" + fmt.Sprintf("%x", time.Now().UnixNano())
	}
	return prefix + "-" + hex.EncodeToString(buf[:])
}
